import json

# This script will update README.md from uf2families.json

section_marker = "#### Family list"
preface_text = "\nThis section is automatically generated by an external tool.\n\n"
suffix_text = "\n"
field_list = (("ID", "id"), ("Short Name", "short_name"), ("Description", "description"))

def output_markdown(output, field_list, row_iterator):
    total_fields = 0
    for field in field_list:
        output.write("|")
        output.write(field[0])
        total_fields += 1
    output.write("|\n")

    for count in range(total_fields):
        output.write("|-")
    output.write("|\n")

    for row in row_iterator:
        for field in field_list:
            output.write("|")
            output.write(row[field[1]])
        output.write("|\n")

with open("uf2families.json") as json_file:
    families = json.load(json_file)

with open("README.new.md", "w+") as output_file:
    with open("../README.md") as input_file:
        # Find our section

        for line in input_file:
            output_file.write(line)

            if line.startswith(section_marker):
                break

        # Write new data to output_file

        output_file.write(preface_text)
        output_markdown(output_file, field_list, families)
        output_file.write(suffix_text)

        # Skip input file to next section

        skipping = True
        for line in input_file:
            if skipping:
                if line.startswith("#"):
                    skipping = False
                    output_file.write(line)
            else:
                output_file.write(line)
